# Generated by Django 5.0.6 on 2024-07-12 09:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

def insert_default_features(apps,scheme_editor):
    Feature = apps.get_model('collection', 'Features')

    Feature.objects.bulk_create([
        Feature(chosen="translate"),
        Feature(chosen="simplify"),
        Feature(chosen="paraphrase"),
    ])

class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0003_prepopulate'),
    ]

    operations = [

        migrations.RunPython(insert_default_features, migrations.RunPython.noop),
    ]
